---
name: Bug Report
description: Report a bug in the RetroLogin plugin
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out this form to help us understand and fix the issue.

        ## Quick Checklist
        - [ ] I have searched for existing issues to avoid duplicates
        - [ ] I am using the latest version of RetroLogin
        - [ ] I can reproduce the bug consistently

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is. What happened?
      placeholder: 'The retro login styles are not loading when...'
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        Please provide step-by-step instructions to reproduce the bug.
        Use numbered list format:
        1. First step
        2. Second step
        3. ...
      placeholder: |
        1. Go to wp-login.php
        2. Enter valid credentials
        3. Submit the form
        4. See the error
      value: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: 'The retro styles should be applied to the login page.'

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: 'The login page shows default WordPress styles.'

  - type: input
    id: wordpress-version
    attributes:
      label: WordPress Version
      description: Your WordPress version (find in Dashboard → About)
      placeholder: e.g., 6.6.2

  - type: input
    id: plugin-version
    attributes:
      label: RetroLogin Version
      description: The installed version of RetroLogin
      placeholder: e.g., 0.1.0

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser did you use?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    default: 0

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: |
        Additional environment information that might help:
        - PHP version
        - Web server (Apache/Nginx)
        - Local development or production?
        - Any errors in debug.log?
      placeholder: |
        PHP: 8.2
        Server: LocalWP
        Environment: Development
        WP_DEBUG: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain the problem.
        Drag and drop images here.
      placeholder: '![Screenshot](url)'

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem? Links to related discussions?

---

